runtime: go
api_version: go1.8

handlers:
- url: /static
  static_dir: static

- url: /(.*\.css)
  mime_type: text/css
  static_files: ../static/\1
  upload: ../static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: ../static/\1
  upload: ../static/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: ../static/\1
  upload: ../static/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: ../static/\1
  upload: ../static/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: ../static/\1
  upload: ../static/(.*\.json)
  expiration: "1h"

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: ../static/\1
  upload: ../static/(.*\.(ogg|oga))

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: ../static/\1
  upload: ../static/(.*\.otf)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: ../static/\1
  upload: ../static/(.*\.(svg|svgz))

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: ../static/\1
  upload: ../static/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: ../static/\1
  upload: ../static/(.*\.txt)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: ../static/\1
  upload: ../static/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: ../static/\1
  upload: ../static/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: ../static/\1
  upload: ../static/(.*\.woff)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: ../static/\1
  upload: ../static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.(mid|midi|mp3|wav))
  static_files: ../static/\1
  upload: ../static/(.*\.(mid|midi|mp3|wav))

# site root
- url: /
  static_files: ../static/index.html
  upload: ../static/index.html
  expiration: "15m"

# application
- url: /api/.*
  script: _go_app
